Script updates for CentOS and Debian packages

diff --git a/trunk/LinuxExtras/CentOS/Repeater/etc/init.d/repeater_3 b/trunk/LinuxExtras/CentOS/Repeater/etc/init.d/repeater_3
--- a/trunk/LinuxExtras/CentOS/Repeater/etc/init.d/repeater_3
+++ b/trunk/LinuxExtras/CentOS/Repeater/etc/init.d/repeater_3
@@ -10,10 +10,10 @@
 
 if [ $UID -ne 0 ]; then
 	echo
-	     echo "ERROR:  This script must be run as the root user!"
-	     echo "        Please use 'su' or log in as root and try again."
-	     echo
-	     exit 1
+	echo "ERROR:  This script must be run as the root user!"
+	echo "        Please use 'su' or log in as root and try again."
+	echo
+	exit 1
 fi
 
 me=repeater_3
@@ -33,7 +33,7 @@ fi
 # Check that networking is up.
 [ "${NETWORKING}" = "no" ] && exit 1
 
-# Source the $me configuration
+# Source the configuration
 [ -f /etc/sysconfig/$me ] && . /etc/sysconfig/$me
 
 RETVAL=0
@@ -51,7 +51,7 @@ start() {
     echo "PID: $1"
     echo "$1" > /var/run/$me.pid
 # create a watchdog entry to the crontab
-    echo "*/10 * * * * root ps aux | grep $REPEATER_PATH | grep -vq grep || /etc/init.d/repeater_3 start" > /etc/cron.d/repeater_3
+    echo "*/10 * * * * root ps aux | grep $REPEATER_PATH | grep -vq grep || /etc/init.d/$me start" > /etc/cron.d/$me
     return $RETVAL
 }
 
@@ -63,7 +63,7 @@ stop() {
     [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$me
     echo
 # remove watchdog entry from crontab
-    rm -f /etc/cron.d/repeater_3
+    rm -f /etc/cron.d/$me
     return $RETVAL
 }
 
diff --git a/trunk/LinuxExtras/CentOS/Repeater/usr/local/bin/repeater_conf b/trunk/LinuxExtras/CentOS/Repeater/usr/local/bin/repeater_conf
--- a/trunk/LinuxExtras/CentOS/Repeater/usr/local/bin/repeater_conf
+++ b/trunk/LinuxExtras/CentOS/Repeater/usr/local/bin/repeater_conf
@@ -23,6 +23,7 @@
 # 2012-07-10 dl5di    soundmodem configuration with alsa tools integrated
 # 2012-07-11 dl5di    bugfixes, cleanups, first beta release
 # 2012-08-22 dl5di    change dstarrepeater->soundcardrepeater
+# 2012-08-26 dl5di    check if started by root, needed to modify default settings for start script
 #
 # Todo / known issues:
 # - full implementation of soundmodem configuration and Vellemann board
@@ -32,7 +33,15 @@
 # - implement sanity check for config file 
 #   (find/eliminate dupes)
 #
-rev="20120711-beta"
+rev="20120826-beta"
+
+if [ $UID -ne 0 ]; then
+	echo
+	echo "ERROR:  This script must be run as the root user!"
+	echo "        Please use 'su' or log in as root and try again."
+	echo
+	exit 1
+fi
 #
 # usage:
 # 	./repeater_conf <module> [modemtype]
diff --git a/trunk/LinuxExtras/CentOS/ircDDBGateway/usr/local/bin/ircddbgw_conf b/trunk/LinuxExtras/CentOS/ircDDBGateway/usr/local/bin/ircddbgw_conf
--- a/trunk/LinuxExtras/CentOS/ircDDBGateway/usr/local/bin/ircddbgw_conf
+++ b/trunk/LinuxExtras/CentOS/ircDDBGateway/usr/local/bin/ircddbgw_conf
@@ -41,12 +41,21 @@
 # 2012-07-09 dl5di    modification of "select_item" to allow input of 0-value 
 # 2012-08-05 dl5di    starNetPermanent configuration added 
 # 2012-08-17 dl5di    bugfix default callsign
+# 2012-08-26 dl5di    check if started by root, needed to modify default settings for start script 
 #
 # Todo / known issues:
 # - implement sanity check for config file 
 #   (find/eliminate dupes, convert ',' to '.' in decimals)
 #
-rev="20120818beta"
+rev="20120826beta"
+
+if [ $UID -ne 0 ]; then
+	echo
+	echo "ERROR:  This script must be run as the root user!"
+	echo "        Please use 'su' or log in as root and try again."
+	echo
+	exit 1
+fi
 
 function write_value() {
 #
diff --git a/trunk/LinuxExtras/DebianWheezy/Repeater/etc/init.d/repeater_3 b/trunk/LinuxExtras/DebianWheezy/Repeater/etc/init.d/repeater_3
--- a/trunk/LinuxExtras/DebianWheezy/Repeater/etc/init.d/repeater_3
+++ b/trunk/LinuxExtras/DebianWheezy/Repeater/etc/init.d/repeater_3
@@ -17,17 +17,25 @@
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC=repeater             # Introduce a short description here
 NAME=repeater             # Introduce the short server's name here
-DAEMON="dvrptrrepeaterd"
+DAEMON_PATH=dvrptrrepeaterd
 DAEMON_ARGS=""                 # Arguments to run the daemon with
 DAEMON_USER=opendv
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
+if [ $UID -ne 0 ]; then
+	echo
+	echo "ERROR:  This script must be run as the root user!"
+	echo "        Please use 'su' or log in as root and try again."
+	echo
+	exit 1
+fi
+
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 # Exit if the package is not installed
-[ -x $DAEMON ] || exit 0
+[ -x $DAEMON_PATH ] || exit 0
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
@@ -52,13 +60,13 @@ do_start()
 	/etc/init.d/ntp start
 	sleep 2
 
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $DAEMON_USER --exec $DAEMON --test > /dev/null \
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $DAEMON_USER --exec $DAEMON_PATH --test > /dev/null \
 		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $DAEMON_USER --exec $DAEMON -- \
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $DAEMON_USER --exec $DAEMON_PATH -- \
 		$DAEMON_ARGS \
 		|| return 2
 	# create a watchdog entry to the crontab
-	echo "*/10 * * * * root ps aux | grep $DAEMON | grep -vq grep || /etc/init.d/repeater_3 start" > /etc/cron.d/repeater_3
+	echo "*/10 * * * * root ps aux | grep $DAEMON_PATH | grep -vq grep || /etc/init.d/repeater_3 start" > /etc/cron.d/repeater_3
 }
 
 #
@@ -80,7 +88,7 @@ do_stop()
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON_PATH
 	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
 	rm -f $PIDFILE
@@ -120,7 +128,7 @@ case "$1" in
 	esac
 	;;
   status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       status_of_proc "$DAEMON_PATH" "$NAME" && exit 0 || exit $?
        ;;
   #reload|force-reload)
 	#
diff --git a/trunk/LinuxExtras/DebianWheezy/Repeater/usr/bin/repeater_conf b/trunk/LinuxExtras/DebianWheezy/Repeater/usr/bin/repeater_conf
--- a/trunk/LinuxExtras/DebianWheezy/Repeater/usr/bin/repeater_conf
+++ b/trunk/LinuxExtras/DebianWheezy/Repeater/usr/bin/repeater_conf
@@ -23,6 +23,7 @@
 # 2012-07-10 dl5di    soundmodem configuration with alsa tools integrated
 # 2012-07-11 dl5di    bugfixes, cleanups, first beta release
 # 2012-08-24 dl5di    initial version for ARM platform
+# 2012-08-26 dl5di    check if started by root, needed to modify default settings for start script
 #
 # Todo / known issues:
 # - full implementation of soundmodem configuration and Vellemann board
@@ -32,7 +33,16 @@
 # - implement sanity check for config file 
 #   (find/eliminate dupes)
 #
-rev="20120824-beta"
+rev="20120826-beta"
+
+if [ $UID -ne 0 ]; then
+	echo
+	echo "ERROR:  This script must be run as the root user!"
+	echo "        Please use 'su' or log in as root and try again."
+	echo
+	exit 1
+fi
+
 #
 # usage:
 # 	./repeater_conf <module> [modemtype]
@@ -2140,10 +2150,9 @@ function hwsetup(){
     readconfig2
     hwtype${HWTYPE}
     write_value $CFG hwtype_${MODULE} "$HWTYPE"
-    cat /etc/default/${hwname[$HWTYPE]} | grep "REPEATER_PATH" > /etc/default/repeater_$MODULE
-    cat /etc/default/${hwname[$HWTYPE]} | grep "REPEATER_OPTIONS" | sed "s/\"$/ $MODULE\"/" >> /etc/default/repeater_$MODULE
-    rm -f /etc/init.d/repeater_$MODULE
-    ln /etc/init.d/repeater /etc/init.d/repeater_$MODULE 
+    cat /etc/default/${hwname[$HWTYPE]} | grep "DAEMON_PATH" > /etc/default/repeater_$MODULE
+    cat /etc/default/${hwname[$HWTYPE]} | grep "DAEMON_ARGS" | sed "s/\"$/ $MODULE\"/" >> /etc/default/repeater_$MODULE
+    cat /etc/default/${hwname[$HWTYPE]} | grep "DAEMON_USER" | sed "s/\"$/ $MODULE\"/" >> /etc/default/repeater_$MODULE
     echo "OK ($HWTYPE)"
     echo " "
     return $RET
diff --git a/trunk/LinuxExtras/DebianWheezy/ircDDBGateway/etc/init.d/ircddbgateway b/trunk/LinuxExtras/DebianWheezy/ircDDBGateway/etc/init.d/ircddbgateway
--- a/trunk/LinuxExtras/DebianWheezy/ircDDBGateway/etc/init.d/ircddbgateway
+++ b/trunk/LinuxExtras/DebianWheezy/ircDDBGateway/etc/init.d/ircddbgateway
@@ -25,13 +25,13 @@ PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if not started as root (required for tapi control)
-#if [ $UID -ne 0 ]; then
-#	echo
-#	echo "ERROR:  This script must be run as the root user!"
-#	echo "        Please use 'su' or log in as root and try again."
-#	echo
-#	exit 1
-#fi
+if [ $UID -ne 0 ]; then
+	echo
+	echo "ERROR:  This script must be run as the root user!"
+	echo "        Please use 'su' or log in as root and try again."
+	echo
+	exit 1
+fi
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
diff --git a/trunk/LinuxExtras/DebianWheezy/ircDDBGateway/usr/bin/ircddbgw_conf b/trunk/LinuxExtras/DebianWheezy/ircDDBGateway/usr/bin/ircddbgw_conf
--- a/trunk/LinuxExtras/DebianWheezy/ircDDBGateway/usr/bin/ircddbgw_conf
+++ b/trunk/LinuxExtras/DebianWheezy/ircDDBGateway/usr/bin/ircddbgw_conf
@@ -23,12 +23,21 @@
 # ...
 # 2012-08-12 dl5di    initial version for Debian systems
 # 2012-08-24 dl5di    fixes on ARM system/DVRPTR-NET
+# 2012-08-26 dl5di    check if started by root, needed to modify default settings for start script
 #
 # Todo / known issues:
 # - implement sanity check for config file 
 #   (find/eliminate dupes, convert ',' to '.' in decimals)
 #
-rev="dvrptrnet-20120823beta"
+rev="dvrptrnet-20120826beta"
+
+if [ $UID -ne 0 ]; then
+	echo
+	echo "ERROR:  This script must be run as the root user!"
+	echo "        Please use 'su' or log in as root and try again."
+	echo
+	exit 1
+fi
 
 function write_value() {
 #
